name: Build and deploy to NuGet
on: push

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      shell: cmd
      run: |
        dotnet build -p:Configuration=Release
    - name: Package and upload
      shell: cmd
      run: |
        git clone https://github.com/nblockchain/fsx
        fsx\Tools\fsi.bat fsx\Tools\nugetPush.fsx 0.93 ${{secrets.NUGET_API_KEY}}
